# Generated by Django 5.2 on 2025-06-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_userpasswordtracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordTracker',
        ),
    ]
