# Generated by Django 5.2.3 on 2025-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_remove_tweet_image_tweetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_images'),
        ),
        migrations.DeleteModel(
            name='TweetImage',
        ),
    ]
