# Generated by Django 5.2.3 on 2025-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweets',
            field=models.IntegerField(default=0),
        ),
    ]
