# Generated by Django 5.2.3 on 2025-07-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_profile_likes_given_profile_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes_given',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tweets',
        ),
    ]
