# Generated by Django 5.2.3 on 2025-07-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_remove_profile_likes_given_remove_profile_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
